name: Bot Deploy Test

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Bu tugma orqali qo'lda ishga tushirish imkonini beradi

jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Serverga ulanish testi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: echo "Ulanish muvaffaqiyatli! Serverda ishlayapman."
